apiVersion: v1
kind: Secret
metadata:
  name: developer-be-secret
  labels:
    app: developer-be-secret
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc}}