{{- if .Values.tool_chain.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: toolchain-svc
  labels:
    svc: toolchain-svc
spec:
  ports:
    - port: 8059
      targetPort: 8059
      protocol: TCP
  selector:
    app: toolchain
---
apiVersion: v1
kind: Service
metadata:
  name: porting-advisor-svc
  labels:
    svc: porting-advisor-svc
spec:
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: porting-advisor
{{- end }}
