apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: applcm
  name: applcm
spec:
  selector:
    matchLabels:
      io.kompose.service: applcm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applcm
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: applcm
          env:
            - name: LOG_DIR
              value: /var/log/applcm
            - name: LISTEN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SSL_ENABLED
              value: {{ quote .Values.ssl.enabled }}
            {{- if .Values.ssl.enabled }}
            - name: SSL_KEY_STORE_PATH
              value: /opt/mec/applcm/ssl/keystore.p12
            - name: SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: applcm-keystore-secret
                  key: keystorePassword
            - name: SSL_KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: applcm-keystore-secret
                  key: keystoreType
            - name: SSL_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: applcm-keystore-secret
                  key: keyAlias
            {{- end }}
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: applcm-jwt-secret
                  key: publicKey
            - name: DEPLOY_TYPE
              value: helm
            - name: MEP_PORT
              value: "30088"
            - name: PROMETHEUS_PORT
              value: "30000"
          ports:
            - containerPort: 8282
          resources: {}
          volumeMounts:
            {{- if .Values.ssl.enabled }}
            - mountPath: /opt/mec/applcm/ssl
              name: applcm-keystore
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: applcm-log
              mountPath: /var/log/applcm
            {{- end }}
      volumes:
        {{- if .Values.ssl.enabled }}
        - name: applcm-keystore
          secret:
            secretName: {{ .Values.ssl.keystoreSecretName }}
            items:
              - key: keystore.p12
                path: keystore.p12
                mode: 0600
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: applcm-log
          hostPath:
            path: /var/log/edgegallery/applcm
        {{- end }}
      hostname: applcm
      restartPolicy: Always
status: {}
