{{- if .Values.jwt.use_default_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: applcm-jwt-secret
  labels:
    app: applcm
type: Opaque
stringData:
  publicKey: |-
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA00p8zLQdZG0mTdY495Et
    4aKDSihffzAzrD4zqa9MChEMeiOLvGbhcLSp/dlaVBNrs7so+h3OOU6yiOqt/X7o
    JWHDFjpw4Ob/cE2ZF1CZB4fSxKjxliC0M6d99s6vbxPIFrYNejAjRgSb4J932F8r
    PZPYtqosh1F3C8nAR/fssPHBErolbfL6ulUvW2FqD2+DWVIYIZsWgR80FEUmebCV
    kaNrceMco61kwa3KIhuqtXmKb9mlusicKR80jM5nzHt9nM6dQjkDXv5V2iNeIXnw
    FjtcEu+YUd2WozvXyRDez3Js22jJSKSl37ujUeeD8yM6JLhYDgHJ425O+czbr1AL
    eQIDAQAB
{{- end }}