apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: applcm
  name: applcm
spec:
  selector:
    matchLabels:
      io.kompose.service: applcm
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applcm
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: applcm
          env:
            - name: LOG_DIR
              value: /var/log/applcm
            - name: LISTEN
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: applcm-jwt-secret
                  key: publicKey
            - name: DEPLOY_TYPE
              value: helm
            - name: MEP_PORT
              value: "30088"
            - name: PROMETHEUS_PORT
              value: "30000"
          ports:
            - containerPort: 8282
          resources: {}
      hostname: applcm
      restartPolicy: Always
status: {}
