images:
  apiHandlerInfra:
    repository: edgegallery/api-handler-infra
    tag: stable
    pullPolicy: Always
  meoBpmnInfra:
    repository: edgegallery/bpmn-infra
    tag: stable
    pullPolicy: Always
  meoCatalogDbAdapter:
    repository: edgegallery/catalog-db-adapter
    tag: stable
    pullPolicy: Always
  mecmEsr:
    repository: edgegallery/mecm-esr
    tag: stable
    pullPolicy: Always
  meoRequestDbAdapter:
    repository: edgegallery/request-db-adapter
    tag: stable
    pullPolicy: Always
  mecmCatalog:
    repository: edgegallery/mecm-catalog
    tag: stable
    pullPolicy: Always
  mariadb:
    repository: mariadb
    tag: 10.1
    pullPolicy: Always