apiVersion: v1
kind: Service
metadata:
  name: vfc-catalog
  labels:
    svc: vfc-catalog
spec:
  type: NodePort
  ports:
    - name: "8806"
      nodePort: 30107
      port: 8806
      targetPort: 8806
  selector:
    app: vfc-catalog
---
apiVersion: v1
kind: Service
metadata:
  name: packagemanager
  labels:
    svc: vfc-catalog
spec:
  ports:
    - name: "8806"
      port: 8806
      targetPort: 8806
  selector:
    app: vfc-catalog
