apiVersion: apps/v1
kind: Deployment
metadata:
  name: vfc-catalog
  namespace: default
  labels:
    app: vfc-catalog
spec:
  selector:
    matchLabels:
      app: vfc-catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: vfc-catalog
    spec:
      containers:
        - name: vfc-catalog
          image: {{ .Values.images.mecmCatalog.repository }}:{{ .Values.images.mecmCatalog.tag }}
          imagePullPolicy: {{ .Values.images.mecmCatalog.pullPolicy }}
          ports:
            - containerPort: 8806
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root123
            - name: ESR_PORT
              value: "8181"
            - name: AUTH_MOD_IP
              value: 159.138.61.155
            - name: AUTH_MOD_PORT
              value: "8067"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: vfc-catalog-pv
      volumes:
        - name: vfc-catalog-pv
          hostPath:
            path: /var/run/docker.sock