{{- if .Values.appstore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: appstore-configmap
data:
  application.properties: |
    #### Spring config ####
    # Spring port
    spring.server.port=8066
    #### postgreSQL config ####
    postgres.ip=appstore-be-postgres-svc
    postgres.database=marketplacedb
    postgres.port=5434
    postgres.username=marketplace
    postgres.password=edgegallery
    #### Service Center config ####
    servicecenter.ip=service-center
    servicecenter.port=30100
    servicecomb.name=mec-appstore
    ### ServiceComb ###
    servicecomb.rest.prot=8099
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appstore-be-postgres-initdb-configmap
data:
  postgres.sql: |
    CREATE DATABASE "marketplacedb";

    \c marketplacedb;

    CREATE TABLE catalog_package_table (
    	VERSIONID                VARCHAR(200)       NOT NULL,
    	PACKAGEADDRESS           VARCHAR(200)       NULL,
    	ICONADDRESS              VARCHAR(200)       NULL,
    	SIZE                     VARCHAR(100)       NULL,
    	FILESTRUCTURE            TEXT               NULL,
    	CREATETIME               TIMESTAMP          NULL,
    	SHORTDESC	             TEXT		        NULL,
    	APPNAME                  VARCHAR(100)       NULL,
    	VERSION                  VARCHAR(20)        NULL,
    	APPLICATIONTYPE          VARCHAR(300)       NULL,
    	MARKDOWNCONTENT          TEXT			    NULL,
    	AFFINITY                 VARCHAR(100)       NULL,
    	APPID                    VARCHAR(100)       NULL,
    	USERID                   VARCHAR(100)       NULL,
    	USERNAME                 VARCHAR(100)       NULL,
    	CONSTRAINT catalog_package_table_pkey PRIMARY KEY (VERSIONID)
    );

    CREATE TABLE APP_TABLE (
    	APPID                    VARCHAR(200)       NOT NULL,
    	APPNAME                  VARCHAR(100)       NULL,
    	APPLICATIONTYPE          VARCHAR(300)       NULL,
    	SHORTDESC	             TEXT		        NULL,
    	PROVIDER                 VARCHAR(300)       NULL,
    	APPINTRODUCTION		     TEXT			    NULL,
    	DOWNLOADCOUNT            INT                NULL,
    	AFFINITY                 VARCHAR(100)       NULL,
    	USERID                   VARCHAR(100)       NULL,
    	USERNAME                 VARCHAR(100)       NULL,
    	CREATETIME               TIMESTAMP          NULL,
    	MODIFYTIME               TIMESTAMP          NULL,
      SCORE                    NUMERIC(2,1)       NULL,
    	CONSTRAINT app_table_pkey PRIMARY KEY (APPID)
    );

    CREATE TABLE CSAR_PACKAGE_SCORE (
        COMMENTID                serial,
        USERID                   VARCHAR(100)       NULL,
        USERNAME                 VARCHAR(100)       NULL,
        APPID                    VARCHAR(200)       NOT NULL,
        COMMENTS                 TEXT               NULL,
        SCORE                    NUMERIC(2,1)       NULL,
        COMMENTTIME              TIMESTAMP          NULL,
        CONSTRAINT csar_package_score_pkey PRIMARY KEY (COMMENTID)
    );

    CREATE USER marketplace WITH PASSWORD 'edgegallery';
    GRANT ALL PRIVILEGES ON DATABASE marketplacedb TO marketplace;
    GRANT SELECT ON all tables in schema public TO marketplace;
    GRANT INSERT ON all tables in schema public TO marketplace;
    GRANT DELETE ON all tables in schema public TO marketplace;
    GRANT UPDATE ON all tables in schema public TO marketplace;
{{- end }}
