{{- if .Values.appstore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: appstore-postgres-secret
  labels:
    app: appstore-be-postgres
type: Opaque
data:
  POSTGRES_USER: bWFya2V0cGxhY2U=
  POSTGRES_PASSWORD: ZWRnZWdhbGxlcnk=
{{- end }}