{{- if .Values.appstore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: appstore-be-secret
  labels:
    app: appstore-be-secret
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.appstore.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.appstore.postgres.password | b64enc}}
{{- end }}