apiVersion: v1
kind: Service
metadata:
  name: developer-fe-svc
  labels:
    svc: developer-fe-svc
spec:
  {{- if not .Values.global.ingress.enabled }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.expose.port }}
      targetPort: 8080
      protocol: TCP
      {{- if not .Values.global.ingress.enabled }}
      nodePort: {{ .Values.expose.nodePort }}
      {{- end }}
  selector:
    app: developer-fe