apiVersion: v1
kind: Secret
metadata:
  name: developer-fe-secret
  labels:
    app: developer-fe-secret
type: Opaque
data:
  CLIENT_ID: {{ .Values.security.oauth2.client_id | b64enc}}
  CLIENT_SECRET: {{ .Values.security.oauth2.client_secret | b64enc}}