apiVersion: v1
kind: Service
metadata:
  name: applcm
  labels:
    app: applcm
spec:
  selector:
    app: applcm
  type: NodePort
  ports:
    - port: {{ .Values.expose.applcm.port }}
      targetPort: 8282
      nodePort: {{ .Values.expose.applcm.nodePort }}
