apiVersion: v1
kind: Service
metadata:
  name: api-handler-infra
  labels:
    svc: api-handler-infra
spec:
  type: NodePort
  ports:
  - name: "8080"
    nodePort: 30108
    port: 8080
    targetPort: 8080
  selector:
    app: api-handler-infra