apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-handler-infra
  namespace: default
  labels:
    app: api-handler-infra
spec:
  selector:
    matchLabels:
      app: api-handler-infra
  replicas: 1
  template:
    metadata:
      labels:
        app: api-handler-infra
    spec:
      containers:
        - name: api-handler-infra
          image: {{ .Values.images.apiHandlerInfra.repository }}:{{ .Values.images.apiHandlerInfra.tag }}
          imagePullPolicy: {{ .Values.images.apiHandlerInfra.pullPolicy }}
          ports:
            - containerPort: 8080
          args:
            - /app/start-app.sh
          env:
            - name: APP
              value: api-handler-infra
            - name: AUTH_MODULE_ENDPOINT
              value: 159.138.61.155:8067
            - name: DB_ADMIN_PASSWORD
              value: so_Admin123
            - name: DB_ADMIN_USERNAME
              value: so_admin
            - name: DB_HOST
              value: mariadb
            - name: DB_PASSWORD
              value: so_Admin123
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: so_admin
            - name: JVM_ARGS
              value: -Xms64m -Xmx512m