apiVersion: v1
kind: Service
metadata:
  name: service-center
  labels:
    app: service-center
spec:
  selector:
    app: service-center
  ports:
    - port: 30100
      name: service-center
      targetPort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: service-center-front
  labels:
    app: service-center-front
spec:
  selector:
    app: service-center
  type: NodePort
  ports:
    - port: 30103
      name: service-center-front
      targetPort: 30103
      nodePort: 30130