apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-center
  labels:
    app: service-center
spec:
  selector:
    matchLabels:
      app: service-center
  replicas: 1
  template:
    metadata:
      labels:
        app: service-center
    spec:
      containers:
        - name: service-center
          image: edgegallery/service-center:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30100