apiVersion: v1
kind: Service
metadata:
  name: helm-plugin
  labels:
    app: helm-plugin
spec:
  selector:
    app: helm-plugin
  type: NodePort
  ports:
  - port: {{ .Values.expose.helmplugin.port }}
    targetPort: 8081
    nodePort: {{ .Values.expose.helmplugin.nodePort }}
