{{- if .Values.mecm.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: common-ca-certificates-pv-claim0
  name: common-ca-certificates-pv-claim0
spec:
  storageClassName: ca-certificates-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
{{- end }}