{{- if .Values.mecm.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-claim1
  name: mariadb-claim1
spec:
  storageClassName: mariadb-confd-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
{{- end }}