{{- if .Values.mecm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mecm-fe-secret
  labels:
    app: mecm-fe-secret
type: Opaque
data:
  CLIENT_ID: {{ .Values.mecm.oauth2.client_id | b64enc}}
  CLIENT_SECRET: {{ .Values.mecm.oauth2.client_secret | b64enc}}
{{- end }}