apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-db-adapter
  name: catalog-db-adapter
spec:
  selector:
    matchLabels:
      io.kompose.service: catalog-db-adapter
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-db-adapter
    spec:
      containers:
      - args:
        - /app/wait-for.sh
        - -q
        - -t
        - "300"
        - dbhost:3306
        - --
        - /app/start-app.sh
        env:
        - name: APP
          value: catalog-db-adapter
        - name: DB_ADMIN_PASSWORD
          value: so_Admin123
        - name: DB_ADMIN_USERNAME
          value: so_admin
        - name: DB_HOST
          value: mariadb
        - name: DB_PASSWORD
          value: catalog123
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: cataloguser
        - name: JVM_ARGS
          value: -Xms64m -Xmx512m
        image: {{ .Values.images.meoCatalogDbAdapter.repository }}:{{ .Values.images.meoCatalogDbAdapter.tag }}
        imagePullPolicy: {{ .Values.images.meoCatalogDbAdapter.pullPolicy }}
        name: catalog-db-adapter
        ports:
        - containerPort: 8082
        resources: {}
        volumeMounts:
        - mountPath: /app/ca-certificates
          name: catalog-db-adapter-claim0
        - mountPath: /app/config
          name: catalog-db-adapter-claim1
      hostname: catalog-db-adapter-so-testlab-onap-org
      restartPolicy: Always
      volumes:
      - name: catalog-db-adapter-claim0
        persistentVolumeClaim:
          claimName: common-ca-certificates-pv-claim0
      - name: catalog-db-adapter-claim1
        persistentVolumeClaim:
          claimName: catalog-db-adapter-claim1
status: {}