apiVersion: v1
kind: Service
metadata:
  name: request-db-adapter
  labels:
    svc: request-db-adapter
spec:
  type: NodePort
  ports:
    - name: "8083"
      nodePort: 30106
      port: 8083
      targetPort: 8083
  selector:
    app: request-db-adapter