apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-db-adapter
  namespace: default
  labels:
    app: request-db-adapter
spec:
  selector:
    matchLabels:
      app: request-db-adapter
  replicas: 1
  template:
    metadata:
      labels:
        app: request-db-adapter
    spec:
      containers:
        - name: request-db-adapter
          image: {{ .Values.images.meoRequestDbAdapter.repository }}:{{ .Values.images.meoRequestDbAdapter.tag }}
          imagePullPolicy: {{ .Values.images.meoRequestDbAdapter.pullPolicy }}
          ports:
            - containerPort: 8083
          args:
            - /app/wait-for.sh
            - -q
            - -t
            - "300"
            - dbhost:3306
            - --
            - /app/start-app.sh
          env:
            - name: APP
              value: request-db-adapter
            - name: DB_ADMIN_PASSWORD
              value: so_Admin123
            - name: DB_ADMIN_USERNAME
              value: so_admin
            - name: DB_HOST
              value: mariadb
            - name: DB_PASSWORD
              value: so_Admin123
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: so_admin
            - name: JVM_ARGS
              value: -Xms64m -Xmx512m