global:
  ingress:
    enabled: false
persistence:
  enabled: false
  type: nfs
expose:
  port: 8067
  nodePort: 30067
images:
  repository: edgegallery/user-mgmt
  tag: stable
  pullPolicy: Always
postgres:
  username: usermgmt
  password: edgegallery
  dbname: usermgmtdb
  httpPoolMaxTotal: 200
  httpPoolDefaultMaxPerRoute: 100
  httpPoolConnectTimeout: 10000
  httpPoolConnectionRequestTimeout: 500
  httpPoolSocketTimeout: 15000
cors:
  allow_origins: "*"
redis:
  password: edgegallery
  timeout: 1800
  verification_timeout: 60
  max_total: 1000
  max_idle: 50
  max_wait_millis: 100000
sms:
  enabled: false
#  url:
#  app_key:
#  app_secret:
#  sender:
#  template_id:
#  signature:
#  status_call_back:
jwt:
  use_auto_generated_key_pair: true
#  key_pair_secret_name:
#  key_pair_secret_key:
#  key_pair_alias:
#  key_pair_password:
oauth:
  clients:
    - client_id: developer-fe
      client_secret: 47a37d56ff1e1134d5c65d8e3a29ebfe3c1ca9c543de48b3f6ab0101c3c4621034425299e872e1ae
      client_url:
    - client_id: appstore-fe
      client_secret: 47a37d56ff1e1134d5c65d8e3a29ebfe3c1ca9c543de48b3f6ab0101c3c4621034425299e872e1ae
      client_url:
    - client_id: mecm-fe
      client_secret: 47a37d56ff1e1134d5c65d8e3a29ebfe3c1ca9c543de48b3f6ab0101c3c4621034425299e872e1ae
      client_url: