apiVersion: v1
kind: Secret
metadata:
  name: user-mgmt-secret
  labels:
    app: user-mgmt
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc}}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc}}
  {{- if .Values.sms.enabled }}
  SMS_URL: {{ .Values.sms.url | b64enc}}
  SMS_APP_KEY: {{ .Values.sms.app_key | b64enc}}
  SMS_APP_SECRET: {{ .Values.sms.app_secret | b64enc}}
  SMS_SENDER: {{ .Values.sms.sender | b64enc}}
  SMS_TEMPLATE_ID: {{ .Values.sms.template_id | b64enc}}
  SMS_APP_SIGNATURE: {{ .Values.sms.signature | b64enc}}
  SMS_STATUS_CALL_BACK: {{ .Values.sms.status_call_back | b64enc}}
  {{- end }}
  {{- if not .Values.jwt.use_auto_generated_key_pair }}
  JWT_KEY_PAIR_ALIAS: {{ .Values.jwt.key_pair_alias | b64enc}}
  JWT_KEY_PAIR_PASSWORD: {{ .Values.jwt.key_pair_password | b64enc}}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-mgmt-redis-secret
  labels:
    app: user-mgmt-redis
type: Opaque
data:
  redis.conf: {{ "requirepass " | b64enc}}{{ .Values.redis.password | b64enc}}