apiVersion: v1
kind: Secret
metadata:
  name: mecm-fe-secret
  labels:
    app: mecm-fe-secret
type: Opaque
stringData:
  clientId: {{ .Values.security.oauth2.client_id }}
  clientSecret: {{ .Values.security.oauth2.client_secret }}