apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: toolchain
spec:
  serviceName: "toolchain-svc"
  selector:
    matchLabels:
      app: toolchain
  replicas: 1
  template:
    metadata:
      labels:
        app: toolchain
    spec:
      initContainers:
        - name: init-service-center
          image: busybox:1.28.3
          command: ['sh', '-c', "until nslookup service-center; do echo waiting for service-center; sleep 2; done"]
      containers:
        - name: toolchain
          image: {{ .Values.images.tool_chain.repository }}:{{ .Values.images.tool_chain.tag }}
          imagePullPolicy: {{ .Values.images.tool_chain.pullPolicy }}
          ports:
            - containerPort: 8059
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: toolchain-log
              mountPath: /var/log/toolchain
            {{- end }}
            - name: tool-chain-pvc
              mountPath: /opt/portadv/portadmin
        - name: porting-advisor
          image: {{ .Values.images.porting_advisor.repository }}:{{ .Values.images.porting_advisor.tag }}
          imagePullPolicy: {{ .Values.images.porting_advisor.pullPolicy }}
          ports:
            - containerPort: 8084
          securityContext:
            privileged: true
          volumeMounts:
            - name: tool-chain-pvc
              mountPath: /opt/portadv/portadmin
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: toolchain-log
          hostPath:
            path: /edgegallery_datas/tool-chain/log
        {{- else}}
        - name: tool-chain-pvc
          emptyDir: {}
        {{- end }}
  {{- if and .Values.persistence.enabled (eq .Values.persistence.type "nfs") }}
  volumeClaimTemplates:
    - metadata:
        name: tool-chain-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi
  {{- end }}