apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecesr
  namespace: default
  labels:
    app: mecesr
spec:
  selector:
    matchLabels:
      app: mecesr
  replicas: 1
  template:
    metadata:
      labels:
        app: mecesr
    spec:
      containers:
        - name: mecesr
          image: {{ .Values.images.mecmEsr.repository }}:{{ .Values.images.mecmEsr.tag }}
          imagePullPolicy: {{ .Values.images.mecmEsr.pullPolicy }}
          ports:
            - containerPort: 8181
          env:
            - name: MYSQL_PASSWD
              value: root123
            - name: AUTH_MODULE_ENDPOINT
              value: 159.138.61.155:8067