apiVersion: v1
kind: Service
metadata:
  name: esr
  labels:
    svc: mecesr
spec:
  type: NodePort
  ports:
    - name: "8181"
      nodePort: 30105
      port: 8181
      targetPort: 8181
  selector:
    app: mecesr
---
apiVersion: v1
kind: Service
metadata:
  name: mecesr
  labels:
    svc: mecesr
spec:
  ports:
    - name: "38181"
      port: 38181
      targetPort: 8181
  selector:
    app: mecesr