{{- if .Values.appstore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: appstore-fe-secret
  labels:
    app: appstore-fe-secret
type: Opaque
data:
  CLIENT_ID: {{ .Values.appstore.oauth2.client_id | b64enc}}
  CLIENT_SECRET: {{ .Values.appstore.oauth2.client_secret | b64enc}}
{{- end }}