{{- if .Values.mecm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
     io.kompose.service: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --innodb-flush-log-at-trx-commit=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123
        image: mariadb:10.1.43
        name: mariadb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: mariadb-claim0
        - mountPath: /etc/mysql/conf.d
          name: mariadb-claim1
      hostname: mariadb-so-testlab-onap-org
      restartPolicy: Always
      volumes:
      - name: mariadb-claim0
        persistentVolumeClaim:
          claimName: mariadb-claim0
      - name: mariadb-claim1
        persistentVolumeClaim:
          claimName: mariadb-claim1
status: {}
{{- end }}