{{- if .Values.developer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: developer-be-secret
  labels:
    app: developer-be-secret
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.developer.postgres.username | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.developer.postgres.password | b64enc}}
{{- end }}