apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-db-adapter-claim1
  name: catalog-db-adapter-claim1
spec:
  storageClassName: catalog-db-adapter-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}