{{- if .Values.user_mgmt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-mgmt-configmap
data:
  application.properties: |
    ##### Redis config #####
    redis.ip=user-mgmt-redis-svc
    redis.port=6379
    redis.timeout=1800
    redis.verificationTimeout=900
    redis.maxTotal=1000
    redis.maxIdle=50
    redis.maxWaitMillis=100000

    #### postgreSQL config ####
    postgres.ip=user-mgmt-postgres-svc
    postgres.port=5432
    http.pool.maxTotal=200
    http.pool.defaultMaxPerRoute=100
    http.pool.connectTimeout=10000
    http.pool.connectionRequestTimeout=500
    http.pool.socketTimeout=15000

    #### Service Center config ####
    servicecenter.ip=service-center
    servicecenter.port=30100

    #### SMS config ####
    sms.enabled={{ .Values.user_mgmt.sms.enabled }}

    #### jwt cer path ####
    {{- if not .Values.user_mgmt.jwt.use_auto_generated_key_pair }}
    jwt.keyPair.path=/usr/app/keyPair
    {{- end  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: usermgmt-postgres-initdb-configmap
data:
  postgres.sql: |
    CREATE DATABASE "usermgmtdb";

    \c usermgmtdb;

    CREATE TABLE if not exists tbl_tenant (
      	TENANTID            VARCHAR(100)      PRIMARY KEY NOT NULL,
      	USERNAME            VARCHAR(50)       NOT NULL,
      	PASSWORD            VARCHAR(100)      NOT NULL,
      	COMPANY             VARCHAR(50)       NULL,
      	TELEPHONENUMBER     VARCHAR(20)       NOT NULL,
      	GENDER              VARCHAR(10)       NULL,
      	CONSTRAINT USERNAME UNIQUE (username),
      	CONSTRAINT TELEPHONENUMBER UNIQUE (telephonenumber)

    );

    CREATE TABLE if not exists tbl_tenant_role (
     	TENANTID            VARCHAR(100)      NOT NULL,
      	ROLEID              INTEGER           NOT NULL
    );

    CREATE TABLE if not exists tbl_admin (
      	TENANTID            VARCHAR(100)      PRIMARY KEY NOT NULL,
      	USERNAME            VARCHAR(50)       NOT NULL,
      	PASSWORD            VARCHAR(100)      NOT NULL,
      	COMPANY             VARCHAR(50)       NULL,
      	TELEPHONENUMBER     VARCHAR(20)       NOT NULL,
      	GENDER              VARCHAR(10)       NULL,
      	PERMISSIONS         VARCHAR(500)      NULL
    );


    CREATE TABLE if not exists tbl_role (
        ID                   INTEGER                PRIMARY KEY NOT NULL,
    	PLATFORM             VARCHAR(50)            NOT NULL,
    	ROLE		         VARCHAR(50)            NOT NULL
    );

    insert into tbl_role (ID, PLATFORM, ROLE) values(1, 'APPSTORE', 'GUEST');
    insert into tbl_role (ID, PLATFORM, ROLE) values(2, 'APPSTORE', 'TENANT');
    insert into tbl_role (ID, PLATFORM, ROLE) values(3, 'APPSTORE', 'ADMIN');

    insert into tbl_role (ID, PLATFORM, ROLE) values(4, 'DEVELOPER', 'GUEST');
    insert into tbl_role (ID, PLATFORM, ROLE) values(5, 'DEVELOPER', 'TENANT');
    insert into tbl_role (ID, PLATFORM, ROLE) values(6, 'DEVELOPER', 'ADMIN');

    insert into tbl_role (ID, PLATFORM, ROLE) values(7, 'MECM', 'GUEST');
    insert into tbl_role (ID, PLATFORM, ROLE) values(8, 'MECM', 'TENANT');
    insert into tbl_role (ID, PLATFORM, ROLE) values(9, 'MECM', 'ADMIN');

    CREATE TABLE IF NOT EXISTS oauth_client_details(
        client_id VARCHAR(256) PRIMARY KEY,
        resource_ids VARCHAR(256),
        client_secret VARCHAR(256),
        scope VARCHAR(256),
        authorized_grant_types VARCHAR(256),
        web_server_redirect_uri VARCHAR(256),
        authorities VARCHAR(256),
        access_token_validity INTEGER,
        refresh_token_validity INTEGER,
        additional_information VARCHAR(4096),
        autoapprove VARCHAR(256)
    );

    INSERT INTO oauth_client_details (client_id, client_secret, scope, authorized_grant_types, web_server_redirect_uri, additional_information, autoapprove)
    {{- if eq .Values.expose.type "ingress" }}
    {{- if .Values.expose.ingress.tls.enabled }}
    VALUES ('appstore-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token', 'https://{{ .Values.expose.ingress.hosts.appstore }}/login', '{"logout_url":"https://{{ .Values.expose.ingress.hosts.appstore }}/auth/logout"}', 'true');
    {{- else  }}
    VALUES ('appstore-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token', 'http://{{ .Values.expose.ingress.hosts.appstore }}/login', '{"logout_url":"http://{{ .Values.expose.ingress.hosts.appstore }}/auth/logout"}', 'true');
    {{- end  }}
    {{- end  }}
    {{- if eq .Values.expose.type "nodePort" }}
    VALUES ('appstore-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token', 'http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.appstore_fe.nodePort }}/login', '{"logout_url":"http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.appstore_fe.nodePort }}/auth/logout"}', 'true');
    {{- end  }}

    INSERT INTO oauth_client_details (client_id, client_secret, scope, authorized_grant_types, web_server_redirect_uri, additional_information, autoapprove)
    {{- if eq .Values.expose.type "ingress" }}
    {{- if .Values.expose.ingress.tls.enabled }}
    VALUES ('developer-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token','https://{{ .Values.expose.ingress.hosts.developer }}/login', '{"logout_url":"https://{{ .Values.expose.ingress.hosts.developer }}/auth/logout"}', 'true');
    {{- else  }}
    VALUES ('developer-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token','http://{{ .Values.expose.ingress.hosts.developer }}/login', '{"logout_url":"http://{{ .Values.expose.ingress.hosts.developer }}/auth/logout"}', 'true');
    {{- end  }}
    {{- end  }}
    {{- if eq .Values.expose.type "nodePort" }}
    VALUES ('developer-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token','http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.developer_fe.nodePort }}/login', '{"logout_url":"http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.developer_fe.nodePort }}/auth/logout"}', 'true');
    {{- end  }}

    INSERT INTO oauth_client_details (client_id, client_secret, scope, authorized_grant_types, web_server_redirect_uri, additional_information, autoapprove)
    {{- if eq .Values.expose.type "ingress" }}
    VALUES ('mecm-meo-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token', 'http://{{ .Values.expose.ingress.hosts.mecm }}/login', '{"logout_url":"http://{{ .Values.expose.ingress.hosts.mecm }}/auth/logout"}', 'true');
    {{- end  }}
    {{- if eq .Values.expose.type "nodePort" }}
    VALUES ('mecm-meo-fe', '$2a$10$548/srs3y35mEWjebe7oWuw.g8oOvIndmYz0juQwrsuvnXibCfdai', 'all', 'authorization_code,refresh_token', 'http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.mecm_fe.nodePort }}/login', '{"logout_url":"http://{{ .Values.expose.nodePort.ip }}:{{ .Values.expose.nodePort.mecm_fe.nodePort }}/auth/logout"}', 'true');
    {{- end  }}

    CREATE USER usermgmt WITH PASSWORD 'edgegallery';
    GRANT ALL PRIVILEGES ON DATABASE usermgmtdb TO usermgmt;
    GRANT SELECT ON all tables in schema public TO usermgmt;
    GRANT INSERT ON all tables in schema public TO usermgmt;
    GRANT DELETE ON all tables in schema public TO usermgmt;
    GRANT UPDATE ON all tables in schema public TO usermgmt;
{{- end }}