{{- if .Values.user_mgmt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-svc
  namespace: default
  labels:
    svc: user-mgmt-svc
spec:
  {{- if eq .Values.expose.type "nodePort" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.expose.nodePort.user_mgmt.port }}
      targetPort: 8067
      protocol: TCP
      {{- if eq .Values.expose.type "nodePort" }}
      nodePort: {{ .Values.expose.nodePort.user_mgmt.nodePort }}
      {{- end }}
  selector:
    app: user-mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-postgres-svc
  namespace: default
  labels:
    svc: user-mgmt-postgres-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: user-mgmt-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-redis-svc
  namespace: default
  labels:
    svc: user-mgmt-redis-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: user-mgmt-redis
{{- end }}