apiVersion: v1
kind: Secret
metadata:
  name: mep-secret
  labels:
    app: mep-secret
type: Opaque
stringData:
  clientId: {{ .Values.security.oauth2.clientId }}
  clientSecret: {{ .Values.security.oauth2.clientSecret }}