apiVersion: v1
kind: Secret
metadata:
  name: mep-secret
  namespace: mep
  labels:
    app: mep-secret
type: Opaque
stringData:
  postgresUsername: {{ .Values.postgres.username }}
  postgresPassword: {{ .Values.postgres.password }}