# mep pod
---
apiVersion: v1
kind: Pod
metadata:
  name: mep
  namespace: mep
  labels:
    app: mep
spec:
  containers:
    - image: edgegallery/mep:latest
      imagePullPolicy: Always
      name: mep-pod
      ports:
        - containerPort: 8088
        - containerPort: 8443
      env:
        - name: SSL_ROOT
          value: "/etc/mepssl"
        - name: MEP_SSL_MODE
          value: "0"
      volumeMounts:
        - name: mepssl
          mountPath: "/etc/mepssl"
          readOnly: true
  volumes:
    - name: mepssl
      secret:
        secretName: mepssl-secret