# postgres servcie
---
apiVersion: v1
kind: Service
metadata:
  name: mep-postgres-svc
  namespace: mep
spec:
  selector:
    app: mep-postgres
  type: ClusterIP
  ports:
    - port: 5432
# mep service
---
apiVersion: v1
kind: Service
metadata:
  name: mep-service
  namespace: mep
spec:
  selector:
    app: mep
  type: NodePort
  ports:
    - port: 8088
      name: mep-port
      nodePort: 30088
    - port: 8443
      name: mep-https-port
      nodePort: 30443
# kong service
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: mep
spec:
  selector:
    app: apigw-kong
  type: NodePort
  ports:
    - port: 8000
      name: proxy
    - port: 8443
      name: proxy-ssl
    - port: 8001
      name: admin-api
    - port: 8444
      name: admin-api-ssl