apiVersion: v1
kind: Service
metadata:
  name: catalog-db-adapter
  labels:
    svc: catalog-db-adapter
spec:
  type: NodePort
  ports:
    - name: "8082"
      nodePort: 30103
      port: 8082
      targetPort: 8082
  selector:
    app: catalog-db-adapter