apiVersion: v1
kind: Service
metadata:
  name: appstore-be-svc
  labels:
    svc: appstore-be-svc
spec:
  type: NodePort
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
      nodePort: 30099
  selector:
    app: appstore-be
---
apiVersion: v1
kind: Service
metadata:
  name: appstore-be-postgres-svc
  labels:
    svc: appstore-be-postgres-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: appstore-be-postgres