apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn-infra
  namespace: default
  labels:
    app: bpmn-infra
spec:
  selector:
    matchLabels:
      app: bpmn-infra
  replicas: 1
  template:
    metadata:
      labels:
        app: bpmn-infra
    spec:
      containers:
        - name: bpmn-infra
          image: {{ .Values.images.meoBpmnInfra.repository }}:{{ .Values.images.meoBpmnInfra.tag }}
          imagePullPolicy: {{ .Values.images.meoBpmnInfra.pullPolicy }}
          ports:
            - containerPort: 8081
          args:
            - /app/start-app.sh
          env:
            - name: APP
              value: bpmn-infra
            - name: DB_ADMIN_PASSWORD
              value: so_Admin123
            - name: DB_ADMIN_USERNAME
              value: so_admin
            - name: DB_HOST
              value: mariadb
            - name: DB_PASSWORD
              value: so_Admin123
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: so_admin
            - name: ESR_HOST
              value: 10.43.157.168
            - name: JVM_ARGS
              value: -Xms64m -Xmx512m
            - name: PACKAGE_MGR_HOST
              value: 159.138.38.104