image:
  repository: edgegallery/mecm-applcm
  tag: stable
  pullPolicy: Always
persistence:
  enabled: false
expose:
  port: 8282
  nodePort: 30101
jwt:
  useDefaultSecret: true
ssl:
  enabled: false
  keystoreSecretName:
  keystorePassword:
  keystoreType:
  keyAlias: