dependencies:
  - name: service-center
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.service-center.enabled
  - name: user-mgmt
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.user-mgmt.enabled
  - name: appstore-be
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.appstore-be.enabled
  - name: appstore-fe
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.appstore-fe.enabled
  - name: developer-be
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.developer-be.enabled
  - name: developer-fe
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.developer-fe.enabled
  - name: mecm-be
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.mecm-be.enabled
  - name: mecm-fe
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.mecm-fe.enabled
  - name: tool-chain
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.tool-chain.enabled