dependencies:
  - name: service-center
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.service-center.enabled
  - name: user-mgmt
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.user-mgmt.enabled
  - name: appstore
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.appstore.enabled
  - name: developer
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.developer.enabled
  - name: mecm
    version: 1.0.0
    repository: https://edgegallery.github.io/helm-charts
    condition: global.mecm.enabled