## Global configuration
global:
  service-center:
    enabled: true
  user-mgmt:
    enabled: true
  appstore-be:
    enabled: true
  appstore-fe:
    enabled: true
  developer-be:
    enabled: true
  developer-fe:
    enabled: true
  mecm-be:
    enabled: true
  mecm-fe:
    enabled: true
  tool-chain:
    enabled: true
  security:
    authServerAddress:
  ingress:
    enabled: false
    tls:
      enabled: false
      useDefaultSecret: true
    annotations:
      bodySize: 20m
    hosts:
      auth:
      developer:
      appstore:
      mecm:

# Sub charts
## Configuration values for the user-mgmt dependency
##
user-mgmt:
#  persistence:
#    enabled: false
#    type: nfs
#  images:
#    repository: edgegallery/user-mgmt
#    tag: stable
#    pullPolicy: Always
#  postgres:
#    username: usermgmt
#    password: edgegallery
#    dbname: usermgmtdb
#  cors:
#    allowOrigins: "*"
#  redis:
#    password: edgegallery
#    timeout: 1800
#    verificationTimeout: 60
#    maxTotal: 1000
#    maxIdle: 50
#    maxWaitMillis: 100000
#  sms:
#    enabled: false
#    url:
#    appKey:
#    appSecret:
#    sender:
#    templateId:
#    signature:
#    statusCallBack:
#  jwt:
#    useDefaultSecret: true
  oauth:
    clients:
      appstore:
#        clientId: appstore-fe
#        clientSecret: c5c94984df13697132641b84cf728aed16f06d83908bfe2781f405591697230b29c3199f31e74d9a
        clientUrl:
      developer:
#        clientId: developer-fe
#        clientSecret: c5c94984df13697132641b84cf728aed16f06d83908bfe2781f405591697230b29c3199f31e74d9a
        clientUrl:
      mecm:
#        clientId: mecm-fe
#        clientSecret: c5c94984df13697132641b84cf728aed16f06d83908bfe2781f405591697230b29c3199f31e74d9a
        clientUrl:

# Sub charts
## Configuration values for the appstore-be dependency
##
#appstore-be:
#  persistence:
#    enabled: false
#  type: nfs
#  images:
#    repository: edgegallery/appstore-be
#    tag: stable
#    pullPolicy: Always
#  postgres:
#    username: appstore
#    password: edgegallery
#    dbname: appstoredb


# Sub charts
## Configuration values for the appstore-fe dependency
##
#appstore-fe:
#  persistence:
#    enabled: false
#    oauth2:
#      clientId: appstore-fe
#      clientSecret: Changeme_123
#  images:
#    repository: edgegallery/appstore-fe
#    tag: stable
#    pullPolicy: Always
#  expose:
#    port: 8443
#    nodePort: 30091

# Sub charts
## Configuration values for the developer-be dependency
##
#developer-be:
#  persistence:
#    enabled: false
#    type: nfs
#  images:
#    repository: edgegallery/developer-be
#    tag: stable
#    pullPolicy: Always
#  postgres:
#    username: developer
#    password: edgegallery
#    dbname: developerdb

# Sub charts
## Configuration values for the developer-fe dependency
##
#developer-fe:
#  persistence:
#    enabled: false
#    oauth2:
#      clientId: developer-fe
#      clientSecret: Changeme_123
#  images:
#    repository: edgegallery/developer-fe
#    tag: stable
#    pullPolicy: Always
#  expose:
#    port: 8443
#    nodePort: 30092

# Sub charts
## Configuration values for the mecm-be dependency
##
#mecm-be:
#  images:
#    apiHandlerInfra:
#      repository: edgegallery/api-handler-infra
#      tag: stable
#      pullPolicy: Always
#    meoBpmnInfra:
#      repository: edgegallery/bpmn-infra
#      tag: stable
#      pullPolicy: Always
#    meoCatalogDbAdapter:
#      repository: edgegallery/catalog-db-adapter
#      tag: stable
#      pullPolicy: Always
#    mecmEsr:
#      repository: edgegallery/mecm-esr
#      tag: stable
#      pullPolicy: Always
#    meoRequestDbAdapter:
#      repository: edgegallery/request-db-adapter
#      tag: stable
#      pullPolicy: Always
#    mecmCatalog:
#      repository: edgegallery/mecm-catalog
#      tag: stable
#      pullPolicy: Always
#    mariadb:
#      repository: mariadb
#      tag: 10.1
#      pullPolicy: Always

# Sub charts
## Configuration values for the mecm-fe dependency
##
#mecm-fe:
#  persistence:
#    enabled: false
#    oauth2:
#      clientId: mecm-fe
#      clientSecret: Changeme_123
#  images:
#    repository: edgegallery/mecm-fe
#    tag: stable
#    pullPolicy: Always
#  expose:
#    port: 8443
#    nodePort: 30093

# Sub charts
## Configuration values for the tool-chain dependency
##
#tool-chain:
#  persistence:
#    enabled: false
#    type: nfs
#  images:
#    toolChain:
#      repository: edgegallery/toolchain
#      tag: stable
#      pullPolicy: Always
#    portingAdvisor:
#      repository: edgegallery/porting-advisor
#      tag: stable
#      pullPolicy: Always