apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-handler-infra-claim1
  name: api-handler-infra-claim1
spec:
  storageClassName: api-handler-infra-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}