apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-confd-pv
  labels:
    type: local
spec:
  storageClassName: mariadb-confd-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/mariadb/conf.d"