apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-claim0
  name: mariadb-claim0
spec:
  storageClassName: docker-entrypoint-initdb-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}